## Spectral Dataset

In [1]:
import pandas as pd
import numpy as np

from data_loader.dataset import SpectralDataset
from data_loader.dataset import Device

## Data loading

In [2]:
data_path = "../spectral_data"
dataset = SpectralDataset(data_path, device= Device.BIO_SCIENCE)

## Testing the loading functions

In [3]:
devices= Device.get_devices()
device_names = Device.get_device_names()

for _device, _device_name in zip(devices, device_names):
    dataset = SpectralDataset(data_path, device=_device)
    print(_device_name, len(dataset), sep='\t|\t')

BIO_SCIENCE	|	1591
SCAN_CODER	|	1684
LOW_COST	|	807


## Testing dataloading for scan coder

In [4]:
dataset= SpectralDataset(data_path, Device.SCAN_CODER)
dataset[0]

array([0.052081, 0.063122, 0.064846, 0.103572, 0.114943, 0.120739,
       0.107806, 0.091979, 0.083951, 0.575549, 0.586088, 0.592532,
       3.      ], dtype=float32)

## Testing dataloading for low cost spectrometer

In [5]:
dataset = SpectralDataset(data_path, Device.LOW_COST)
spectral = dataset[0]
len(dataset)

spectral[0][:50]

array([0.65213066, 0.6477052 , 0.6434713 , 0.63935727, 0.63523173,
       0.6313745 , 0.6279762 , 0.6244545 , 0.62106264, 0.6178428 ,
       0.6149054 , 0.6121445 , 0.6093943 , 0.60693544, 0.6047515 ,
       0.60255784, 0.6005062 , 0.5986285 , 0.59718597, 0.5960724 ,
       0.59523547, 0.5946899 , 0.5947127 , 0.5948768 , 0.59546345,
       0.5963935 , 0.5973958 , 0.59842086, 0.59971756, 0.6011697 ,
       0.60268176, 0.60383797, 0.60508394, 0.6062775 , 0.6078311 ,
       0.6092528 , 0.6109181 , 0.61242914, 0.61402005, 0.6156764 ,
       0.6175508 , 0.619544  , 0.62167   , 0.6234482 , 0.62568796,
       0.62782526, 0.63040966, 0.6330416 , 0.6359563 , 0.63901013],
      dtype=float32)

## Testing dataloading for high end spectrometer

In [13]:
dataset = SpectralDataset(data_path, Device.BIO_SCIENCE)
res = dataset[0]
res[res.columns[-1]].values.astype(np.float32)

array([  0.      ,  60.      , 100.      , ...,  70.833336,  70.833336,
        70.833336], shape=(3648,), dtype=float32)

In [10]:
res[res.columns[-1]].values

array([  0.      ,  60.      , 100.      , ...,  70.833336,  70.833336,
        70.833336], shape=(3648,), dtype=float32)